### ISSUE TITLE
Feature Request: Globally Installed Extensions

### ISSUE THREAD

**Issue by ProfessorManhattan** [cyfrost/install-gnome-extensions#1]
Thanks for the project! It saved me a lot of work. At first, I tried to use puppeteer and Firefox to install my extensions automatically but I found this project. It's working just fine. +1 for adding a feature to install the extensions globally.

Can I just move the extension folders in ~/.local/share/gnome-shell/extensions/ to /usr/share/gnome-shell/extensions/?

Also, it would be cool if there was an Ansible module for this

**Comment by cyfrost** [comment]
Hey @ProfessorManhattan many apologies for responding so late, I've been a little out of touch with this project and many others due to other priorities that've come first since quite a while.

Not that it'd help after such a long time, but I'll try to answer: I'm not entirely sure that moving the user extensions directories manually into the global directories would make them available for all users automatically. I believe the glib2.0 schemas for each extension need to be recompiled (which is done once during install AFAIK).

About the Ansible module: It's a great thought especially for sysadmins working with multiple linux boxes. Although I'd have to confess I haven't made anything of that sort myself but I can gladly point you to community made ones [here](https://github.com/PeterMosmans/ansible-role-customize-gnome) and [here](https://github.com/jaredhocutt/ansible-gnome-extensions).

P.S: If you're still using this script for anything more than > GNOME 38, I believe you'll run into issues simply because the script is largely out-of-date. I've since archived this repository in favor of a better and well maintained fork that exists [here](https://github.com/ToasterUwU/install-gnome-extensions).
