### ISSUE TITLE
I forked and fixed this Script

### ISSUE THREAD

**Issue by ToasterUwU** [cyfrost/install-gnome-extensions#2]
Just letting people know.

This script has not seen an update in 4 years, and probably never will again.

I forked this repo and fixed the script, since the installing didnt work anymore.
It also doesnt require sudo perms for one single command and uses the gnome-extensions install command now, which simplifies the whole process.

Link to the fork with the fixed script: https://github.com/ToasterUwU/install-gnome-extensions

To cyfrost: If you are still around and interested in keeping your script working, feel free to pull my fix and let me know. I will gladly update the text here to reflect this and dont bring people to my fork anymore.

**Comment by cyfrost** [comment]
Hi @ToasterUwU

First of all, thank you for contributions towards forking and updating the script and making it usable for everyone.

Unfortunately, these days, I'm unable to find time to contribute to this script and keep it up-to-date due to other priorities in life that come first. Consequentially, I've decided on moving this to archive and redirecting peeps to your fork.

Thanks again for your contributions.
